"""created metrics

Revision ID: 771e6499f79e
Revises: 
Create Date: 2025-11-28 22:06:11.391328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '771e6499f79e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('html_cashes',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('word', sa.Float(), nullable=False),
    sa.Column('citation', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('html_cashes')
    # ### end Alembic commands ###
